env: standard
runtime: nodejs20

handlers:
  - url: /static
    static_dir: build/static
    secure: always

  - url: /(.*\.(json|ico|js))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js)$
    secure: always

  - url: .*
    static_files: build/index.html
    upload: build/index.html
    secure: always